name: KGphotography
favicon: null
layout_spectrum: 0.7580685243010521
typography_spectrum: 0.12776500289328396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edf1f4'
    - '#fa8d25'
    - '#978276'
    - '#475624'
    - '#b8c1be'
  brandStrength: 0.75
  lightness: 0.0632183556444943
  saturation: 0.3912600639741868
  rhythmicContrast: 0.34003119822591543
purpose: []
